---
# tasks file for zabbix-server-new-2

# 1.Updating the system (uncomment if necessary)

# - name: Updating the system
#   yum:
#     name: '*'
#     state: latest
#   become: yes
#
# 2.Switching off SELinux (uncomment if necessary)
#
# - name: Switching off SELinux
#   selinux:
#     state: disabled
#   become: yes

- name: Installing Zabbix repository
  become: True
  yum:
    name: '{{ z_repo }}'
    state: present

- name: Installing a list of packages
  become: True
  yum:
    name:
      - zabbix-server-mysql  # This is the server package
      - zabbix-web-mysql
      - zabbix-agent
    state: present

- name: Replacing the commented entry with a valid parameter ( DBHost )
  become: True
  replace:
    dest: '{{ z_config }}'
    regexp: '^# DBHost=localhost$'
    replace: 'DBHost={{ z_dblocation }}'

- name: Replacing the commented entry with a valid parameter ( DBPassword )
  become: True
  replace:
    dest: '{{ z_config }}'
    regexp: '^# DBPassword=$'
    replace: 'DBPassword={{ z_dbpass }}'

- name: Starting and enabling Zabbix
  become: True
  service:
    name: zabbix-server
    state: started
    enabled: True

- name: Adding a timezone to the web config of Zabbix
  become: True
  lineinfile:
    path: '{{ z_webconfig }}'
    insertafter: '# php_value date.timezone'
    line: '        php_value date.timezone {{ z_timezone }}'

- name: Starting and enabling httpd
  become: True
  service:
    name: httpd
    state: started
    enabled: True

- name: Starting and enabling zabbix-agent
  become: True
  service:
    name: zabbix-agent
    state: started
    enabled: True
