---
# tasks file for ansible-role-zabbix-server

# 1.Updating the system (uncomment if necessary)

# - name: Updating the system
#   yum:
#     name: '*'
#     state: latest
#   become: yes
#
# 2.Switching off SELinux (uncomment if necessary)
#
# - name: Switching off SELinux
#   selinux:
#     state: disabled
#   become: yes

- name: Installing Zabbix repository
  become: True
  yum:
    name: '{{ z_repo }}'
    state: present
  register: task_result_1
  retries: 3
  delay: 2
  until: task_result_1 is success

- name: Installing a list of packages
  become: True
  yum:
    name:
      - zabbix-server-mysql  # This is the server package
      - zabbix-web-mysql
      - zabbix-agent
    state: present
  register: task_result_2
  retries: 3
  delay: 2
  until: task_result_2 is success

- name: Replacing the commented entry with a valid parameter ( DBHost )
  become: True
  replace:
    dest: '{{ z_config }}'
    regexp: '^# DBHost=localhost$'
    replace: 'DBHost={{ z_dblocation }}'

#- name: Putting DB name into my.cnf
#  become: True
#  ini_file:
#    path: /etc/my.cnf
#    section: client
#    option: user
#    value: zabbix
#    backup: yes

#- name: Putting DB name into my.cnf
#  become: True
#  ini_file:
#    path: /etc/my.cnf
#    section: client
#    option: password
#    value: 1
#    backup: yes

- name: Replacing the commented entry with a valid parameter ( DBPassword )
  become: True
  replace:
    dest: '{{ z_config }}'
    regexp: '^# DBPassword=$'
    replace: 'DBPassword={{ z_dbpass }}'

# - name: Importing DB scheme
#   shell: 'zcat /usr/share/doc/zabbix-server-mysql*/create.sql.gz | mysql -uzabbix -p1'
#   args:
#     executable: /bin/bash

- name: Counting the quantity of tables
  shell: |
    set -o pipefail
    mysqlshow --user=root --password=1 zabbix | grep -v "Database: zabbix" | grep -v Tables | grep -v +-- | wc -l
  register: tables_quantity
  changed_when: False                                                     # checking the exit code of the command
  ignore_errors: true

- name: Print
  debug:
    var: tables_quantity.stdout

- name: Importing DB scheme
  mysql_db:
    name: zabbix
    login_user: zabbix
    login_password: 1
    state: import
    target: /usr/share/doc/zabbix-server-mysql-4.2.1/create.sql.gz
  when: tables_quantity.stdout == "0"

- name: Starting and enabling Zabbix
  become: True
  service:
    name: zabbix-server
    state: started
    enabled: True

- name: Adding a timezone to the web config of Zabbix
  become: True
  lineinfile:
    path: '{{ z_webconfig }}'
    insertafter: '# php_value date.timezone'
    line: '        php_value date.timezone {{ z_timezone }}'

- name: Starting and enabling httpd
  become: True
  service:
    name: httpd
    state: started
    enabled: True

- name: Starting and enabling zabbix-agent
  become: True
  service:
    name: zabbix-agent
    state: started
    enabled: True
