---
  - name: Add Zabbix repositories
    apt:
      deb: "{{ zabbix_apt_url }}"
      state: present
      update_cache: true
    register: status
    until: status is succeeded

  - name: Renewing packages list
    apt:
      update_cache: true
    register: status
    until: status is succeeded

  - name: Install Zabbix
    apt:
      name:  zabbix-server-mysql
      state: present
    register: status
    until: status is succeeded

  - name: Install Zabbix front
    apt:
      name: zabbix-frontend-php
      state: present
    register: status
    until: status is succeeded

  - name: Install Zabbix agent
    apt:
      name: zabbix-agent
      state: present
    register: status
    until: status is succeeded

  - name: Install Apache2
    package:
      name: apache2
      state: present
    register: status
    until: status is succeeded

#  - name: Importing
#    mysql_db:
#      name: zabbix
#      login_user: zabbix
#      login_password: 1
#      state: import
#      target: /usr/share/doc/zabbix-server-mysql*/create.sql.gz

  - name: Adding a timezone to the web config of Zabbix
    become: true
    lineinfile:
      path: '/etc/apache2/conf-available/zabbix.conf'
      insertafter: '# php_value date.timezone'
      line: '        php_value date.timezone {{ zabbix_time_zone }}'

  - name: Replacing ( DBHost )
    replace:
      dest: '{{ zabbix_config }}'
      regexp: '^# DBHost=localhost$'
      replace: 'DBHost=localhost'

  - name: Replacing ( DBPassword )
    replace:
      dest: '{{ zabbix_config }}'
      regexp: '^# DBPassword=$'
      replace: 'DBPassword={{ db_pass }}'

  - name: Starting and enabling zabbix-server
    service:
      name: zabbix-server
      state: started
      enabled: true

  - name: Starting and enabling zabbix-agent
    service:
      name: zabbix-agent
      state: started
      enabled: true

  - name: Starting and enabling Apache2
    service:
      name: apache2
      state: started
      enabled: true

  - name: Check  front
    uri:
      url: http://localhost/zabbix/setup.php
      method: GET
      return_content: true
      status_code: 200, 404
      body_format: json
    register: web_result

  - name: Print 2
    debug:
      msg: "{{ web_result }}"
