---
- name: Zabbix installation
  block:
    - name: Add Zabbix repo
      package:
        name: "{{ zabbix_yum_url }}"
        state: present
      register: status
      until: status is succeeded

    - name: Install Zabbix
      yum:
        name:
          - zabbix-server-mysql
          - zabbix-web-mysql
          - zabbix-agent
        state: present
      register: status
      until: status is succeeded

    - name: Install httpd
      package:
        name:
          - httpd
        state: present
      register: status
      until: status is succeeded

    - name: Adding a timezone to the web config of Zabbix
      become: true
      lineinfile:
        path: '/etc/httpd/conf.d/zabbix.conf'
        insertafter: '# php_value date.timezone'
        line: '        php_value date.timezone {{ zabbix_time_zone }}'

    - name: Replacing ( DBHost )
      replace:
        dest: '{{ zabbix_config }}'
        regexp: '^# DBHost=localhost$'
        replace: 'DBHost=localhost'

    - name: Replacing ( DBPassword )
      replace:
        dest: '{{ zabbix_config }}'
        regexp: '^# DBPassword=$'
        replace: 'DBPassword=31415'

    - name: Starting and enabling zabbix-server
      service:
        name: zabbix-server
        state: started
        enabled: true

    - name: Starting and enabling zabbix-agent
      service:
        name: zabbix-agent
        state: started
        enabled: true

    - name: Starting and enabling httpd
      service:
        name: httpd
        state: started
        enabled: true

    - name: Check front
      uri:
        url: http://localhost/zabbix/setup.php
        method: GET
        return_content: true
        status_code: 200, 404
        body_format: json
      register: web_result

    - name: Print 2
      debug:
        msg: "{{ web_result }}"
