---
# handlers file for zabbix-server
- name: Reload Apache
  become: true
  service:
    name: apache2
    state: reloaded

- name: create db zabbix
  mysql_db:
    name: zabbix
    encoding: utf8
    collation: utf8_bin
    login_host: localhost
    login_user: zabbix
    login_password: 1
    state: present

- name: import zabbix db ubuntu
  mysql_db:
    name: zabbix
    login_host: localhost
    login_user: zabbix
    login_password: 1
    state: import
    target: /usr/share/doc/zabbix-server-mysql/create.sql.gz

- name: import zabbix db centos
  mysql_db:
    name: zabbix
    login_host: localhost
    login_user: zabbix
    login_password: 1
    state: import
    target: /usr/share/doc/zabbix-server-mysql-4.2.3/create.sql.gz
